import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { DemoCreateAccount } from "~/components/create-account";
import { buttonVariants } from "~/components/ui/button";
import { Label } from "~/components/ui/label";
import { siteConfig } from "~/config/site";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container grid items-center gap-6 pb-8 pt-6 md:py-10">
        <div className="flex max-w-[980px] flex-col items-start gap-2">
          <h1 className="text-3xl font-extrabold leading-tight tracking-tighter md:text-4xl">
            Beautifully designed components <br className="hidden sm:inline" />
            built with Radix UI and Tailwind CSS.{" "}
          </h1>
          <p className="max-w-[700px] text-lg text-muted-foreground">
            Accessible and customizable components that you can copy and paste
            into your apps. Free. Open Source. And Next.js 13 Ready.
          </p>
          <Label>{hello.isLoading ? "loading..." : hello.data?.greeting}</Label>
        </div>
        <div className="flex gap-4">
          <Link
            href={siteConfig.links.docs}
            target="_blank"
            rel="noreferrer"
            className={buttonVariants()}
          >
            Documentation
          </Link>
          <Link
            target="_blank"
            rel="noreferrer"
            href={siteConfig.links.github}
            className={buttonVariants({ variant: "bright" })}
          >
            GitHub
          </Link>
        </div>
        <div>
          <DemoCreateAccount />
        </div>
      </section>
    </>
  );
};

export default Home;
